
import time

# ENUMS

DEBUG_PRINT_ENABLE = True
DEBUG_MODULE_SERVER = 0
DEBUG_MODULE_CLIENT = 1
DEBUG_MODULE_MOTORS = 2
DEBUG_MODULE_CAMERA = 3

DEBUG_MODULES = {
        DEBUG_MODULE_SERVER : True,
        DEBUG_MODULE_CLIENT : True,
        DEBUG_MODULE_MOTORS : False,
        DEBUG_MODULE_CAMERA : True
    }

DEBUG_MODULE_STRINGS = {
        DEBUG_MODULE_SERVER : "SER",
        DEBUG_MODULE_CLIENT : "CLI",
        DEBUG_MODULE_MOTORS : "PWM",
        DEBUG_MODULE_CAMERA : "CAM"
    }

DEBUG_LEVEL_INFO    = 0
DEBUG_LEVEL_WARNING = 1
DEBUG_LEVEL_ERROR   = 2

def debugPrint(string, module=0, level=0):
    if DEBUG_PRINT_ENABLE and DEBUG_MODULES[module]:
        print("[%s] %s" % (DEBUG_MODULE_STRINGS[module], string))
